package com.egutter.trading.candidates;

import com.egutter.trading.decision.Candidate;
import com.egutter.trading.decision.generator.*;
import com.egutter.trading.stock.StockGroup;
import org.uncommons.maths.binary.BitString;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import static com.egutter.trading.stock.StockMarket.*;
import static java.util.Arrays.asList;

public class GlobalStockMarketCandidates {

    public static List<Candidate> newCandidates() {
        List<? extends Class<? extends BuyTradingDecisionGenerator>> tradingDecisionGenerators = Arrays.asList(FibonacciRetracementGenerator.class,
                StochasticOscillatorGenerator.class,
                MoneyFlowIndexGenerator.class,
                TrailingStopGenerator.class);

        return asList(

        );
    }

    public static List<BitString> chromosomeCandidates() {
        return candidates().stream().map(candidate -> candidate.getChromosome()).collect(Collectors.toList());
    }

    public static List<Candidate> candidates() {
        List<? extends Class<? extends BuyTradingDecisionGenerator>> tradingDecisionGenerators = Arrays.asList(FibonacciRetracementGenerator.class,
                StochasticOscillatorGenerator.class,
                MoneyFlowIndexGenerator.class,
                TrailingStopGenerator.class);

        return asList(
                new Candidate("General", "1010111001111001000100100001101010011000110101000000", tradingDecisionGenerators),

                new Candidate("Developed Countries ETF", "1000010001110011011110111110011100011111111101110001",
                        tradingDecisionGenerators,
                        asList(new StockGroup(DEVELOP_ETF_MARKETS, "0.89", developedMarkets())
                        )),
                new Candidate("Developed Countries ETF", "1010010001110011011101001111111100001111111101111101",
                        tradingDecisionGenerators,
                        asList(new StockGroup(DEVELOP_ETF_MARKETS, "0.89", developedMarkets())
                        )),
                new Candidate("General", "0011010111011111110001111100000011110111100111010001",
                        tradingDecisionGenerators,
                        asList(new StockGroup(TECH_SECTOR, "0.83", techSector()),
                                new StockGroup(FINANCE_SECTOR, "1.00 (8 ops)", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.80 (5 ops)", consumerDiscSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "1.00 (2 ops)", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "1.00 (4 ops)", consumerBasicSector())
                        )), // nice 0.82
                new Candidate("General", "1100110111101100001011010101111100000001010000110011", tradingDecisionGenerators), // nice 0.82
                new Candidate("General",
                        "1110110011100010110111011010010010101101000101000001",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.8", sectors()))), // nice 0.82
                new Candidate("General", "1101100101010001000110111110111101111011011100111101", tradingDecisionGenerators),
                new Candidate("General",
                        "1110110011100010110111010101111100000001000101000010",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.81", sectors()))),
                new Candidate("General",
                        "0111111000011100111100101001010010110001000101000111",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.86", sectors()))),
                new Candidate("Sectors", "1110110011100010110111010101111100100001000101000010", tradingDecisionGenerators), //sectors
                new Candidate("Sectors",
                        "0111111000001100111000111001011100000101001101000000",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.90", sectors()))),
                new Candidate("Sector", "0111111000001100111000111001011100000101001101000011", tradingDecisionGenerators), //sectors
                new Candidate("Sectors",
                        "0100001101100000111000000000011011111111011101110010",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.88", sectors()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.82", consumerBasicSector())
                                )),
                new Candidate("Tech",
                        "0100011100001001101000000011101011101111101111101000",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.89", sectors()),
                                new StockGroup(TECH_SECTOR, "0.82", techSector()),
                                new StockGroup(COMM_SECTOR, "0.80", commSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.81", consumerDiscSector()),
                                new StockGroup(FINANCE_SECTOR, "0.83", financeSector()),
                                new StockGroup(HEALTH_SECTOR, "0.80", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.81", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.83", consumerBasicSector())
                                        )),
                new Candidate("Tech",
                        "0100011100001001101000101011100100001111111111101100",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.89", sectors()),
                                new StockGroup(TECH_SECTOR, "0.86", techSector()),
                                new StockGroup(COMM_SECTOR, "0.84", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.87", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.83", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.82", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.82", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.85", consumerBasicSector())
                        )),
                new Candidate("Tech",
                        "0100011100001001101000101001001011110001111101101110",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.89", sectors()),
                                new StockGroup(TECH_SECTOR, "0.85", techSector()),
                                new StockGroup(COMM_SECTOR, "0.83", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.86", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.82", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.82", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.81", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.84", consumerBasicSector())
                        )),
                new Candidate("Tech", "0101011100001000101000000111101011111111111111101100",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.90", sectors()),
                                new StockGroup(TECH_SECTOR, "0.82", techSector()),
                                new StockGroup(COMM_SECTOR, "0.81", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.83", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.82", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.82", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.81", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.84", consumerBasicSector())
                        )),
                new Candidate("Tech", "0101011100001000101001011011100100001111101111101100",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.89", sectors()),
                                new StockGroup(TECH_SECTOR, "0.85", techSector()),
                                new StockGroup(COMM_SECTOR, "0.82", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.84", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.81", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.82", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.81", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.83", consumerBasicSector())
                        )),
                new Candidate("Tech", "0011000100001010001000001001011100001111111101111111",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.85", sectors()),
                                new StockGroup(TECH_SECTOR, "0.82", techSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.80", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.80", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.80", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.81", consumerBasicSector())
                        )),
                new Candidate("Finance", "0101011100001000101000010111100100001111111111101111",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.89", sectors()),
                                new StockGroup(TECH_SECTOR, "0.83", techSector()),
                                new StockGroup(COMM_SECTOR, "0.82", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.84", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.82", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.82", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.81", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.84", consumerBasicSector())
                        )),
                new Candidate("Finance", "0100011100001001101011011111001100011011111111111101",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.89", sectors()),
                                new StockGroup(TECH_SECTOR, "0.83", techSector()),
                                new StockGroup(COMM_SECTOR, "0.81", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.89", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.85", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.84", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.83", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.85", consumerBasicSector())
                                )),
                new Candidate("Finance", "0100011100001001101000111111001100001001111111111100",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.89", sectors()),
                                new StockGroup(TECH_SECTOR, "0.84", techSector()),
                                new StockGroup(COMM_SECTOR, "0.83", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.89", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.82", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.85", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.82", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.85", consumerBasicSector())
                        )),
                new Candidate("Finance", "0100011100000001101011011111100100011011101111100100",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.89", sectors()),
                                new StockGroup(TECH_SECTOR, "0.82", techSector()),
                                new StockGroup(COMM_SECTOR, "0.80", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.88", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.83", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.82", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.83", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.84", consumerBasicSector())
                        )),
                new Candidate("Communication", "0001010100001010101000000111101100000111111111111111",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.89", sectors()),
                                new StockGroup(TECH_SECTOR, "0.84", techSector()),
                                new StockGroup(COMM_SECTOR, "0.83", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.82", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.82", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.83", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.82", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.84", consumerBasicSector())
                        )),
                new Candidate("Communication", "0100011100101101101000101110100100000001111001111111",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.90", sectors()),
                                new StockGroup(TECH_SECTOR, "0.82", techSector()),
                                new StockGroup(COMM_SECTOR, "0.84", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.87", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.84", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.82", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.82", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.83", consumerBasicSector())
                        )),
                new Candidate("Communication", "0110011100101101101000101111100011100111111001111011",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.90", sectors()),
                                new StockGroup(TECH_SECTOR, "0.82", techSector()),
                                new StockGroup(COMM_SECTOR, "0.84", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.87", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.84", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.82", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.83", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.82", consumerBasicSector())
                        )),
                new Candidate("Communication", "0100011100000100101110101111101100001111111111011110",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.92", sectors()),
                                new StockGroup(TECH_SECTOR, "0.84", techSector()),
                                new StockGroup(COMM_SECTOR, "0.87", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.89", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.84", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.82", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.84", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.84", consumerBasicSector())
                        )),
                new Candidate("Health", "0111111000001100011011111111100100001111110101100111",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.95", sectors()),
                                new StockGroup(TECH_SECTOR, "0.82", techSector()),
                                new StockGroup(COMM_SECTOR, "0.84", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.88", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.80", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.85", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.83", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.83", consumerBasicSector())
                        )),
                new Candidate("Health", "1100111100000001101001001111100100001111111111101111",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.88", sectors()),
                                new StockGroup(TECH_SECTOR, "0.82", techSector()),
                                new StockGroup(FINANCE_SECTOR, "0.84", financeSector()),
                                new StockGroup(HEALTH_SECTOR, "0.88", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.81", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.88", consumerBasicSector())
                        )),
                new Candidate("Consumer disc", "0110011100101101101000001111010100001111111111111011",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.90", sectors()),
                                new StockGroup(TECH_SECTOR, "0.82", techSector()),
                                new StockGroup(COMM_SECTOR, "0.84", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.85", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.85", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.82", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.83", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.86", consumerBasicSector())
                                )),
                new Candidate("Consumer disc", "0100011100000100101100101000100100000001111101101110",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.91", sectors()),
                                new StockGroup(TECH_SECTOR, "0.85", techSector()),
                                new StockGroup(COMM_SECTOR, "0.84", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.88", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.86", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.83", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.84", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.85", consumerBasicSector())
                        )),
                new Candidate("Consumer disc", "0110011100001100101100101001100011100111111101110001",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.90", sectors()),
                                new StockGroup(TECH_SECTOR, "0.85", techSector()),
                                new StockGroup(COMM_SECTOR, "0.85", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.88", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.86", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.83", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.85", industrialSector()),
                                new StockGroup(INNOVATION_SECTOR, "0.80", innovationSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.85", consumerBasicSector())
                        )),
                new Candidate("Consumer basic", "1000010001100011001010111111011100001111111111101110",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.89", sectors()),
                                new StockGroup(TECH_SECTOR, "0.83", techSector()),
                                new StockGroup(COMM_SECTOR, "0.87", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.88", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.84", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.89", healthSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.88", consumerBasicSector())
                        )),
                new Candidate("Consumer basic", "1100111100000001101001001111100100001111111111111110",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.88", sectors()),
                                new StockGroup(TECH_SECTOR, "0.82", techSector()),
                                new StockGroup(COMM_SECTOR, "0.80", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.84", financeSector()),
                                new StockGroup(HEALTH_SECTOR, "0.88", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.81", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.89", consumerBasicSector())
                        )),
                new Candidate("Consumer basic", "0010101001111100010101001111100011111111111111110111",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.89", sectors()),
                                new StockGroup(TECH_SECTOR, "0.85", techSector()),
                                new StockGroup(COMM_SECTOR, "0.81", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.84", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.82", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.86", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.83", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.89", consumerBasicSector())
                        )),
                new Candidate("Consumer basic", "0010101001111100010101011001100100011111111111110110",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.87", sectors()),
                                new StockGroup(TECH_SECTOR, "0.85", techSector()),
                                new StockGroup(COMM_SECTOR, "0.81", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.83", financeSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.81", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.84", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.83", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.89", consumerBasicSector())
                        )),
                new Candidate("Industrial", "1000111000000011101001011011100100000011111101111110",
                        tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.88", sectors()),
                                new StockGroup(TECH_SECTOR, "0.83", techSector()),
                                new StockGroup(COMM_SECTOR, "0.81", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.84", financeSector()),
                                new StockGroup(HEALTH_SECTOR, "0.82", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.87", industrialSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.85", consumerBasicSector())
                        )),
                new Candidate("General", "1101100101010001000110111110111101111011011001001111",
                        tradingDecisionGenerators),

                new Candidate("Sectors", "0111111000001100111000111001011100001111111101101111", tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.95", sectors()),
                                new StockGroup(TECH_SECTOR, "0.85", techSector()),
                                new StockGroup(FINANCE_SECTOR, "0.85", financeSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.83", consumerBasicSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.80", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.84", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.84", industrialSector())
                        )),
                new Candidate("Tech", "1101010100001010101011111101100100101111111101101101", tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.90", sectors()),
                                new StockGroup(TECH_SECTOR, "0.88", techSector()),
                                new StockGroup(COMM_SECTOR, "0.83", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.86", financeSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.85", consumerBasicSector()),
                                new StockGroup(HEALTH_SECTOR, "0.84", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.83", industrialSector())
                        )),
                new Candidate("Comm", "0100011100000100101110101111101100011011111111111101", tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.91", sectors()),
                                new StockGroup(TECH_SECTOR, "0.84", techSector()),
                                new StockGroup(COMM_SECTOR, "0.87", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.89", financeSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.84", consumerBasicSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.84", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.83", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.84", industrialSector())
                        )),
                new Candidate("Finance", "0100011100101001101011011111101100000001111001111111", tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.89", sectors()),
                                new StockGroup(TECH_SECTOR, "0.82", techSector()),
                                new StockGroup(COMM_SECTOR, "0.81", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.89", financeSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.84", consumerBasicSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.84", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.84", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.83", industrialSector())
                        )),
                new Candidate("Cons Basic", "0010101001111100010101001111101100001111111111011110", tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.87", sectors()),
                                new StockGroup(TECH_SECTOR, "0.82", techSector()),
                                new StockGroup(COMM_SECTOR, "0.80", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.82", financeSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.88", consumerBasicSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.80", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.85", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.82", industrialSector())
                        )),
                new Candidate("Cons Disc", "0100011100000100101100101000100100001011111101101100", tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.91", sectors()),
                                new StockGroup(TECH_SECTOR, "0.85", techSector()),
                                new StockGroup(COMM_SECTOR, "0.84", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.88", financeSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.85", consumerBasicSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.86", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.83", healthSector()),
                                new StockGroup(INDUSTRIAL_SECTOR, "0.85", industrialSector())
                        )),
                new Candidate("Health", "1000010001100011001000111101000011101111111011101111", tradingDecisionGenerators,
                        asList(new StockGroup(ETF_SECTORS, "0.91", sectors()),
                                new StockGroup(TECH_SECTOR, "0.81", techSector()),
                                new StockGroup(COMM_SECTOR, "0.85", commSector()),
                                new StockGroup(FINANCE_SECTOR, "0.85", financeSector()),
                                new StockGroup(CONS_BASIC_SECTOR, "0.87", consumerBasicSector()),
                                new StockGroup(CONS_DISC_SECTOR, "0.84", consumerDiscSector()),
                                new StockGroup(HEALTH_SECTOR, "0.89", healthSector())
                        ))
        );
    }
}
